name: Draft Release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    uses: "./.github/workflows/build.yml"
  draft:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
      - uses: actions/download-artifact@v8
        with:
          merge-multiple: true
      - name: Create Draft
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          mv canvas-keyboard-pan.zip "canvas-keyboard-pan-${tag}.zip"

          gh release create "$tag" \
            --title="Canvas Keyboard Pan $tag" \
            --draft \
            --notes="" \
            "canvas-keyboard-pan-${tag}.zip" main.js manifest.json styles.css
